config/routes.rb
Rails.application.routes.draw do
  #resources :home, only: [:index, :secret]
  root 'home#index'
  #get 'home/secret'
  devise_for :users
  resources :events do
  	resources :attendances
  	resources :charges
  end
  #resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :subscription_send

  belongs_to :attendee, class_name: "User"
  belongs_to :event
  validates :stripe_customer_id, presence: true

  def subscription_send
  	@event = Attendance.last.event
  	@attendee = Attendance.last.attendee
  	UserMailer.event_subscription_email(@event, @attendee).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :administrator, class_name: "User"
  has_many :attendances
  has_many :attendees, class_name: "User", through: :attendances
  validate :start_date_cannot_be_created_in_the_past, on: :create
  validate :start_date_cannot_be_updated_when_past, on: :update
  validate :duration_should_modulo_five, :duration_should_not_be_null
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, inclusion: 1..1000
  validates :location, presence: true

  def duration_should_modulo_five
  	errors.add(:duration, "should be modulo five") if
  		!(duration % 5 == 0)
  end

  def duration_should_not_be_null
  	errors.add(:duration, "should not be null or absent") if
  		duration == 0 || !duration.present?
  end

  def start_date_cannot_be_created_in_the_past
  	errors.add(:start_date, "can't be created with past date or absent") if
  		!start_date.present? || start_date < Time.now
  end

  def start_date_cannot_be_updated_when_past
  	errors.add(:start_date, "can't be updated in the past") if
  		start_date < Date.today
	end

  def end_date
    self.start_date + (self.duration).minute
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send

	has_many :administrated_events, foreign_key: 'administrator_id', class_name: "Event"
  has_many :attendances
  has_many :attended_events, foreign_key: 'attended_id', class_name: "Event", through: :attendances

  def welcome_send
  	UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include EventsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :index]
	def index
		@event = Event.find(params[:event_id]) 
	end
	def new
		@event = Event.find(params[:event_id])
		@attendance = Attendance.new
	end
	def create
		#@attendance = Attendance.new(stripe_customer_id: , attendee: current_user, event: Event.find(params[:event_id])
  	# Amount in cents
  	@event = Event.find(params[:event_id])
  	@amount = @event.price * 100

  	customer = Stripe::Customer.create(
    	:email => params[:stripeEmail],
    	:source  => params[:stripeToken]
  	)

  	charge = Stripe::Charge.create(
    	:customer    => customer.id,
    	:amount      => @amount,
    	:description => 'Rails Stripe customer',
    	:currency    => 'eur'
  	)

  	puts "le customer c'est machin chose"
  	puts charge[:customer]

	#rescue Stripe::CardError => e
  	#flash[:error] = e.message
  	#redirect_to new_charge_path

		@attendance = Attendance.new(stripe_customer_id: charge[:customer], attendee: current_user, event: @event)
		if @attendance.save
			# si ça marche, il redirige vers la page d'index du site
  		flash[:success] = "Oh ça va être bat comme on disait d'antan !" #hash depuis l'application.html.erb
    	redirect_to event_path(@event.id)
  	else
  	  	# sinon, il render la view new (qui est celle sur laquelle on est déjà)
  	  flash[:danger] = "Meh si tu payes pas, comment on va s'enrichir, nous ?" #idem
  		render 'new'
  	end
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@event = Event.find(params[:event_id])
	end

	def create
  	# Amount in cents
  	@event = Event.find(params[:event_id])
  	@amount = @event.price * 100

  	customer = Stripe::Customer.create(
    	:email => params[:stripeEmail],
    	:source  => params[:stripeToken]
  	)

  	charge = Stripe::Charge.create(
    	:customer    => customer.id,
    	:amount      => @amount,
    	:description => 'Rails Stripe customer',
    	:currency    => 'eur'
  	)

  	puts "le customer c'est machin chose"
  	puts charge[:customer]

	rescue Stripe::CardError => e
  	flash[:error] = e.message
  	redirect_to new_charge_path
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_administrator, only: [:edit, :update, :destroy]
  def index
  end
  def show
    @event = Event.find(params[:id])
    puts @event.title
  end
	def new
    @event = Event.new
	end
	def create
  	@event = Event.new(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], administrator: current_user, price: params[:price], location: params[:location])
  	if @event.save # essaie de sauvegarder en base @gossip
  	  # si ça marche, il redirige vers la page d'index du site
  	  #flash[:success] = "Oh le beau event !" #hash depuis l'application.html.erb
  	  redirect_to root_path
  	else
  	  # sinon, il render la view new (qui est celle sur laquelle on est déjà)
  	  #flash[:danger] = "Meh sans balloon c'est pas un vrai event" #idem
  	  render 'new'
  	end
  end
  def edit
    @event = Event.find(params[:id])
  end
  def update
    @event = Event.find(params[:id])
    if @event.update(start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], administrator: @event.administrator, price: params[:price], location: params[:location])
      flash[:success] = "Modification saved !"
      redirect_to root_path
    else
      flash[:danger] = "Non modification pas sauvegardée !"
      render :edit
    end
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private 

  def authenticate_administrator
    @event = Event.find(params[:id])
    if current_user == @event.administrator
      true
    else
      false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, only: [:secret]
  def index
  	@events = Event.all
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def already_attendee_or_admin?(event)
		if (current_user == event.administrator) || (event.attendees.include?(current_user))
			true
		else
			false
		end
	end

	def is_admin?(event)
		if current_user == event.administrator
			true
		else
			false
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendances/_stripe_checkout_form.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @event.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @event.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/attendances/index.html.erb
<h1>Privéééé !</h1>
<p>Le nombre de participants à l'event est de : <%= @event.attendees.size %> personnes</p>
<% @event.attendees.each do |attendee| %>
<%= attendee.email %>
<%= attendee.first_name %>
<% end %><br /><br />
<%= "$" * 30 %><br /><br />
<%= link_to "Modifier l'event", edit_event_path(@event.id) %><br /><br />
<%= link_to "Supprime l'event", event_path(@event.id), :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/attendances/new.html.erb
<h1>Rejoins-nous à <%= @event.title %></h1>
<%= render 'stripe_checkout_form' %>
<p>super cool</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @event.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @event.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<h1>Mo-Di-Fi-Ca-Tion</h1>
<%= form_tag url_for(action: 'update'), method: "patch" do %>
	<!--input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"-->
  <!--input type="text" name="gossip_text"-->
  <!--input type="submit" value="Valider"-->
  <%= label_tag 'Start Date' %>
  <%= date_field_tag 'start_date', @event.start_date %>
  <br /> <br />
  <%= label_tag 'Duration' %>
  <%= number_field_tag 'duration', @event.duration %>
  <br /> <br />
  <%= label_tag 'Title' %>
  <%= text_field_tag 'title', @event.title %>
  <br /> <br />
  <%= label_tag 'Description' %>
  <%= text_area_tag 'description', @event.description %>
  <br /> <br />
  <%= label_tag 'Price' %>
  <%= number_field_tag 'price', @event.price %>
  <br /> <br />
  <%= label_tag 'Location' %>
  <%= text_field_tag 'location', @event.location %>
  <br /> <br />
  <%= submit_tag "Create Event" %>
<% end %>

app/views/events/new.html.erb
<h1>crée un event patron</h1>
<%= form_tag url_for(action: 'create'), method: "post" do %>
	<!--input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>"-->
  <!--input type="text" name="gossip_text"-->
  <!--input type="submit" value="Valider"-->
  <%= label_tag 'Start Date' %>
  <%= date_field_tag 'start_date' %>
  <br /> <br />
  <%= label_tag 'Duration' %>
  <%= number_field_tag 'duration' %>
  <br /> <br />
  <%= label_tag 'Title' %>
  <%= text_field_tag 'title' %>
  <br /> <br />
  <%= label_tag 'Description' %>
  <%= text_area_tag 'description' %>
  <br /> <br />
  <%= label_tag 'Price' %>
  <%= number_field_tag 'price' %>
  <br /> <br />
  <%= label_tag 'Location' %>
  <%= text_field_tag 'location' %>
  <br /> <br />
  <%= submit_tag "Create Event" %>
<% end %>

<% if @event.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/events/show.html.erb
<h1>Title : <%= @event.title %></h1>
<p>Description : <%= @event.description %></p>
<p>Email du patron : <%= @event.administrator.email %></p>
<p>Number of inscrit: <%= @event.attendances.size %></p>
<p>Début : <%= @event.start_date %></p>
<p>Fin : <%= @event.end_date %></p>
<p>Lieu : <%= @event.location %></p>
<p>Prix : <%= @event.price %></p>

<% if !already_attendee_or_admin?(@event) %>
<%= link_to 'Inscription', new_event_attendance_path(@event.id) %>
<% else %>
<p>t'es deja inscris arrete de faire le malin</p>
<% end %>

<% if is_admin?(@event) %>
<%= link_to 'Mon Espace Privé', event_attendances_path(@event.id) %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
<div class="d-flex align-content-between flex-wrap">
  <% @events.each do |event| %>
    <div class="card mx-auto mt-4" style="width: 18rem;">
      <img class="card-img-top" src="http://citation-celebre.leparisien.fr/images/personnage-fiction/4189.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%= event.description %></p>
        <%= link_to "En savoir plus", event_path(event.id) %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheEventbriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/jumbotron/jumbotron.css" rel="stylesheet">

  </head>
  <style>body {
    background : red;
  }
  .yes {
    padding-top: 9px;
  }
  li>a {
    color : red;
  }</style>
  <body>
    <center>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <%= link_to "EventBrite", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class => "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Create Event", new_event_path, :class => "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="yes">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            </li>
            <li class="yes">
              <%= link_to "Your Profile" %>
            </li>
          <% else %>
            <li>    
              <%= link_to "Log in", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </center>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>